# name: Deploy project to our server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   ftp-deploy:
#     name: Deploy to FTP Server
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Deploy to FTP Server
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#         with:
#           server: ftp.teanatureltd.com
#           username: teanatureftp@teanatureltd.com
#           password: "7RRW9BXVVTQS"
#           protocol: ftps
#           port: 21

name: Deploy project to our server
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 72.61.233.228
          username: teanatureftp
          password: "PeFiO7osC11plGkZmsKH"
